= SDD 0002 - Naming Scheme

:sdd_author:    Marco Fretz
:sdd_owner:     Marco Fretz
:sdd_reviewers: 
:sdd_status:    draft
include::partial$meta-info-table.adoc[]

[NOTE]
.Summary
====
Defines which layers and scope of (configuration) management we have to help cut this SYN elephant into pieces.
====

== Motivation

The task to manage all the things starting from the kubernetes cluster provisioning to automatically provision and manage services on the cluster and automate and manage (customer) application deployments can be very challenging. Without cutting these into a layered model, it seem impossible to bring in some structure.

=== Goals

* We know which layers / scopes we have, when we in other SDDs talk about them.
* When someone talks or writes about config management on a specific layer, it's clear to others what the scope is

=== Non-Goals

This does not:

* Define how exactly configuration management is done on a layer
* What exact features the VMSF will provide on each level

== Design Proposal

=== User Stories

a) Platty GmbH

* Platform operated by VSHN
* Monitoring done by VSHN
* Deployment done by customer
* Services can be provisioned automatically by the customer

b) Allthethings AG

In addition to a)

* Deployment done by VSHN
* Services provisioned by VSHN as part of the Deplyoments
* Deployment of independent Services provisioned by VSHN

=== Implementation Details/Notes/Constraints

We differentiate between 3 Levels where we or the customer manages things.

==== Managed Platform

The VSHN SYN enabled Kubernetes Cluster

* This adds the VMSFv2 features to the kubernetes cluster and registers the cluster with the VSHN SYNventory (for Inventory, Billing, easy Access, etc.)
* This includes all the services needed to run the VMSFv2

==== Managed Service

Any Service running on top or configured by the VSHN SYN Platform which is managed by VSHN

* Such services are automatically provisioned by the Service Provisioning System and are automatically brought into the VMSFv2
* VSHN or the customer can provision such services in the scope of his Application deployment, manually by creating the specific object in the kubernetes API or using additional GitOps.

==== (Managed) Application

Any customer specific service or application running on top of the VSHN SYN Platform, which is not necessarily managed by VSHN.

* Such deployments can be engineered by using specific kubernetes objects to make use of the VMSF to bring them into Monitoring, Backup and Maintenance
* Applications can be deployed with any method to the cluster (kubernetes manifests manually or via GitOps, Rancher UI, manifests as part of a deployment pipeline, etc.)

=== Risks and Mitigations

There is a risk that we'll have *mixture between Applications and Managed Services*:

* It is very important to make sure that a Managed Service is a well defined VSHN product (Product definition mandatory).
* When we engineer a Service or Application deployment for the customer (for for VSHN Infra / Corp) it's a (Managed) Application, not a Managed Service

Maybe the *naming* here can be a problem and cause confusion

* For some it's hard to get the same understanding of the difference between Service and Application
* Where does the platform start and where does it end? E.g. is the SYN monitoring we run as part of the managed platform a service?
* Is running the platform a service? icon:smile[]

We should think twice about good naming here before this is accepted as it has an impact on basically all other SDDs which are currently in draft status. 

== Alternatives

* We could see Managed Services as part of the Platform?
* Services are Applications too? why differentiate here?

== References
