= SDD 0015 - Secrets Management

:sdd_author:    Tobias Brunner, Simon Rüegg
:sdd_owner:     SIG Security
:sdd_reviewers: Syn Kickstart Group
:sdd_date:      2019-10-28
:sdd_status:    draft
include::partial$meta-info-table.adoc[]

[NOTE]
.Summary
====
The secret management with Vault defines how secrets are stored and retrieved in a secure and auditable way.
====

== Motivation

Securely storing and retrieving secrets is a key part of an application runtime platform. We must ensure that secrets cannot leak and that access to secrets is done in a controlled way. No plaintext secrets must be stored in Git.

=== Goals

* Securely store and retrieve secrets
* Controlled access to secrets
* Auditing of secret access
* Automated handling of secrets as much as possible
* Helper to easily rotate secrets

=== Non-Goals

* Automation for storing static secrets in secret store
* Detailed setup of the VSHN Vault installation

== Design Proposal

To accomplish the stated goals we will rely on https://www.vaultproject.io/[Vault] as a secret store. The following will describe how we intend to setup and configure Vault.

=== Cluster Local Vault

Each SYN managed cluster will have it's own Vault. By default this will be installed on the cluster and managed by the https://wiki.vshn.net/pages/viewpage.action?pageId=151914962[Platform Configuration Management]. If a customer already has a Vault installation it could be reused, instead of installing it on the cluster.

The cluster local Vault can be used by application running on the cluster and will be set up to support the https://www.vaultproject.io/docs/platform/k8s/index.html[various features targeted to K8s].

==== Bootstrapping

The https://wiki.vshn.net/pages/viewpage.action?pageId=151914983[Steward Cluster Agent] will bootstrap the cluster local Vault installation and in coordination with the https://wiki.vshn.net/pages/viewpage.action?pageId=151914981[Lieutenant - Management API] set up the auto unseal, recovery keys and root tokens. An important aspect is to make sure https://wiki.vshn.net/pages/viewpage.action?pageId=157286488[Argo CD] can only apply secrets once the cluster local Vault is ready.

==== Unsealing

The cluster local Vault will be set up to https://learn.hashicorp.com/vault/operations/autounseal-transit[auto unseal] using the VSHN Vault transit secret. This ensures restarting Vault pods won't leave the cluster in an unusable state. The recovery keys generated during setup will be GPG encrypted and [.inline-comment-marker]#centrally stored#. This ensures that even in the event of an outage of the VSHN Vault we are still able to unseal cluster local Vaults.

==== Storage Backend

The https://www.vaultproject.io/docs/configuration/storage/raft.html[[.inline-comment-marker]#Raft storage backend#] will be used by the cluster local Vaults. This simplifies the setup and maintenance of the Vault setups. Even though this feature is still labeled as "Beta", we'll make use of it and will switch to another backend if it proves to be unstable.

==== Backup

There are two parts of Vault which need to be backed up: The storage backend and the unseal keys. Without both of them, either is unusable. The unseal keys will already be stored centrally as discussed. This leaves the storage backend to be backed up. The Raft storage backend provides a https://learn.hashicorp.com/vault/operations/raft-storage#raft-snapshots-for-data-recovery[snapshot functionality] for this very purpose.

=== VSHN Vault

A Vault instance will be operated internally at VSHN. This VSHN Vault instance might also be used for other use cases internal to VSHN, like functioning as a password manager.

==== Unsealing

The https://www.vaultproject.io/docs/concepts/seal.html[unseal keys] will be GPG encrypted and distributed. The exact setup and requirements is to be defined.

==== Transit Secret

The https://www.vaultproject.io/docs/secrets/transit/index.html[transit secret engine] is used to auto unseal cluster local Vault instances. A separate key per cluster is used and the https://www.vaultproject.io/docs/auth/approle.html[AppRole] authentication method to authenticate the clusters. The setup of these parts will be done in coordination by https://wiki.vshn.net/pages/viewpage.action?pageId=151914981[Lieutenant] and https://wiki.vshn.net/pages/viewpage.action?pageId=151914983[Steward].

=== User Stories

==== Story 1: Secrets management for configuration stored in Git

As a user of Syn I can store secrets in the secret management system and the application development description in Git, pointing to the necessary secrets available in the secrets management system. The system takes care of revealing the secret only when applying configuration to the platform. No secrets are stored in Git, especially not unencrypted.

An example: Storing a Kubernetes object of the kind "Secret" in Git only contains a pointer to the secret and not the secret itself. The configuration management system then takes care of retrieving the requested secret during the apply phase on the cluster itself, so the secret never leaves the cluster.

==== [.inline-comment-marker]#Story 2: Securely store and access configuration data#

As a user of Syn I want to securely access secrets from my application running on the platform. Objects of the kind "Secret" are not automatically stored encrypted and are available in quasi-plaintext to the platform. The platform should provide means to access secrets in a more secure way.

==== Story 3: Automated secret management

As a user of Syn I don't want to care about managing secrets and leave this work up to the platform. I want to have access to automatically generated secrets and use them for the purpose they are meant for.

Examples:

* Connection credentials for a Syn managed DB
* Automatically generated encryption secret to be used by an application
* TLS certificate & key to be used by an application

==== Story 4: Rotate secrets

As a user of Syn I want the possibility to rotate secrets. If credentials get leaked or otherwise compromised it should be easy and fast to rotate the affected secrets.

==== Story 5: Provide an audit trail for secrets

As a user of Syn I want the ability to see an audit trail for secrets. At the minimum I want to see when and by whom a certain secret was accessed.

==== Story 6: Provide secrets for encrypted volumes

As a user of Syn I'm using a CSI provider that supports encryption, I've to provide secretes (encryption key passphrase) the CSI provider can use for the LUKS encryption. The cloud provider must not be able to decrypt volumes (no access to the encryption keys).

Storing these secrets on the cluster without encryption is thefore a no-go as it would negate mostly all benefits from disk / volume encryption. Also using the the cloud providers KMS is a no-go.

== Implementation Details

=== Cluster Local Vault Recovery Keys

TBD how and where exactly the recovery keys of the cluster local Vaults will be stored.

== Risks and Mitigations

=== Auto Unseal

A clear risk of the auto unseal setup of cluster local Vaults is, that the token used to authenticate to the VSHN Vault can be used to get access to the Vault's https://www.vaultproject.io/docs/internals/rotation.html[master key]. Therefore special care needs to be taken for handling these tokens. For now the token will be stored in a Kubernetes secret of the respective cluster. If a cluster does not configure https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/[encryption at rest] properly, this token will end up in clear text in the etcd database.

A possible mitigation would be to not enable auto unseal for a cluster local Vault and only have the unseal key distributed in GPG secrets. This would require a manual unseal process for each restart of a Vault pod.

=== VSHN Vault Availability

The central VSHN Vault has a high requirement in regards to availability. Since all cluster local Vaults depend on it for the auto unseal, in case of an outage of the VSHN Vault, cluster local Vaults can not auto unseal anymore. This is only a problem if Vault pods are restarted and/or to bootstrap new clusters. As a disaster recovery measure, the recovery keys for each cluster local Vault are stored GPG encrypted in a central location. This ensures that even in the case of a enduring disaster, cluster local Vaults can be unsealed with these recovery keys.

== Alternatives

=== Central Vault

A possible alternative would be using only a single central Vault installation, instead of cluster local Vaults. The main drawback of this approach is the central point of risk it would create. Also, as stated by the docs, Vault https://learn.hashicorp.com/vault/operations/namespaces[should not be used in a multi tenant environment].

== References

* Kapitan secret reveal:
** https://kapitan.dev/secrets/
** https://github.com/deepmind/kapitan/blob/master/docs/kap_proposals/kap_5_ref_types_redesign.md
* Vault auto unseal using transit encryption (another Vault)
** https://www.vaultproject.io/docs/configuration/seal/transit.html
** https://learn.hashicorp.com/vault/operations/autounseal-transit
* Vault K8s auth - https://www.vaultproject.io/docs/auth/kubernetes.html
