= SDD 0018 - Maintenance Overview

:sdd_author:    Tobias Brunner
:sdd_owner:     SIG Maintenance
:sdd_reviewers: SIG Maintenance
:sdd_date:      2019-11-06
:sdd_status:    speculative
include::partial$meta-info-table.adoc[]

[NOTE]
.Summary
====
Overall description of the several maintenance work which has to be done on a Syn managed platform
====

== Motivation

Regularly maintaining all components on a Syn managed platform ensures stable and secure operations and is a key part of the offering. There are many parts which need to be maintained and each part has it's own maintenance procedures. This means all parts need to be engineered in detail itself, but an overall overview of this needs to be available. This SDD describes these parts and the ideas behind the maintenance per part.

=== Goals

* Describe all maintenance layers
* Give an overview of the available maintenance layers and dependencies

=== Non-Goals

* Describe each maintenance layer in detail

== Design Proposal

Each part of Syn needs it's own maintenance procedure. This SDD lists the overview.

=== Maintenance of: Operating System

Maintaining the Operating System incl. Linux Kernel, Container runtime and more heavily depends on the OS distribution and on the possibilities the cloud offers.

* *Solution 1: Package based updates.* +
Update packages via OS package manager f.e. with a node agent running as DaemonSet or / and scheduled updates provided by the package manager. See also https://wiki.vshn.net/display/SYN/Node+Maintenance+and+Configuration+Research[Node Maintenance and Configuration Research]
* *Solution 2: OS image rollover.* +
Rollover the nodes with a freshly updated image, f.e. using the Larawan pipeline.
* *Solution 3: Leverage possibilities of cloud offering.* +
Some clouds offer automated node maintenance

_SDD to be written..._

=== Maintenance of: Kubernetes Cluster

Maintaining a Kubernetes cluster itself depends heavily on the Kubernetes distribution used. It's about updating to a patch release and also to the next major release.

_SDD to be written..._

=== Maintenance of: Infrastructure Components

Part of infrastructure components are applications running on the Syn managed Kubernetes cluster:

* Operators
* Agents

_SDD to be written... Thoughts:_

Tracking operator releases should be automated and trigger image version updates via configuration management.

Maybe OLM could help here?

Upgrades of operators must be tested very carefully and could eventually also mean that CRDs / CRs must be updated. Argo CD with hooks could help here.

=== Maintenance of: Container Images

Most images inherit a base image `FROM` . This base image needs to be maintained as well as all inheriting images.

https://wiki.vshn.net/pages/viewpage.action?pageId=153847765[SDD#2019-11-05 - Maintenance with Renovate]

_Thoughts:_

A regular scan should detect vulnerabilities and act accordingly.

=== Maintenance of: Syn Infrastructure Components

Tools like Commodore, Kapitan, SYNventory, ... with their dependencies (code maintenance)

_SDD to be written... Thoughts:_

Regular release flow with several stages, automated CI/CD and with the help of renovate?

=== Maintenance of: SaaS tools

Full solutions like GitLab, Atlassian, Gitea, Rocket.Chat and more.

https://wiki.vshn.net/pages/viewpage.action?pageId=153847765[SDD#2019-11-05 - Maintenance with Renovate]

=== Maintenance of: Commodore components

Commodore components are versioned in Git. Updating to a new major version might break things as it can also include newer operators, images, etc. or use new versions of CRDs

https://wiki.vshn.net/pages/viewpage.action?pageId=153847765[SDD#2019-11-05 - Maintenance with Renovate]

=== Maintenance Overview

_Thoughts:_

* Dashboard for Renovate MR overview. Display:
** Deployed version
** New available version
** Changelog / README
** Button to release version

=== User Stories [optional]

 +

=== Implementation Details/Notes/Constraints [optional]

 +

=== Risks and Mitigations [optional]

 +

== Drawbacks [optional]

 +

== Alternatives [optional]

 +

== References

Some links to tools and ideas for doing maintenance.

[cols=",",options="header",]
|===
a|
Name

a|
Description

|https://github.com/renovatebot/renovate[renovate] a|
[.text-gray-dark .mr-2]#Universal dependency update automation tool that fits into your workflows#

____
Renovate supports upgrading dependencies in various types of Docker definition files:

* Docker's `Dockerfile` files
* Docker Compose files
* CircleCI config files
* Kubernetes manifests
* Ansible configuration files
____

Possible downside: https://docs.renovatebot.com/pro/overview/

____
Essentially, it is an alternative to running the `renovate` CLI tool, with the following benefits:

* Stateful job queue for prioritisation of job importance and resumption after interruption
* Embedded job scheduler to remove the need to set up and monitor `cron`
* Webhook listener to enable dynamic reactions to repository events
____

|https://github.com/dependabot[dependabot] a|
____
Automated dependency updates
____

|https://github.com/GoogleCloudPlatform/repository-gardener[repository-gardener] a|
____
The repository gardener maintains code samples by running some automatable tasks. For example, it can automatically update dependencies and then after running tests to ensure they still work, send a Pull Request for the update.
____

|https://newreleases.io/[newreleases.io] a|
____
_Stop wasting your time checking manually if some piece of software you depend on is updated._
____

|GitHub Releases Atom Feed |Releases can be subscribe as an Atom feed. Eg. https://github.com/kubernetes/kubernetes/releases.atom
|===

