= SDD 0024 - Billing Automation based on Prometheus

:sdd_author:    Tobias Brunner
:sdd_owner:     SIG Syn
:sdd_reviewers: 
:sdd_date:      2020-07-07
:sdd_status:    draft
\include::partial$meta-info-table.adoc[]

[NOTE]
.Summary
====
Automated billing of services is a crucial part of doing business. This SDD describes a way for automated billing based on data collected by Prometheus.
====

== Motivation

Service billing must be fully automated and be able to bill services based on the defined products. It must be reliable and secure and flexible enough to support different billing models. As Prometheus is already available on all clusters and billing is defined to be based on metrics, the already collected data can be reused to bill based on that data. By making this concept flexible enough, it should be usable for most billing needs.

=== Goals

* Process for automated billing
* Fully based on Prometheus for data gathering and storing
* Long-term and secure billing data storage
* Plugable data sources

=== Non-Goals

* Invention of new ways of data storage
* Support for a particular billing system
* Define a billing model

== Design Proposal

The key part of the design is to use core functionality of Prometheus and the PromQL query language. This means that all data is present as metrics in Prometheus TSDB. As an overview, the following parts are involved:

* Data is collected on the source cluster using the in-cluster Prometheus
* Metric series which are needed for billing purposes are sent via the https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write[remote_write] functionality to a central billing service. Sent samples are limited using the `write_relabel_configs` configuration option.
* The central billing service consists of a Thanos setup, data is received by the https://thanos.io/components/receive.md/[Thanos receiver].
* An authentication and authorization component in front of the Thanos receiver makes sure the received data is sane and it adds an identifying label to the metric, for example the Lieutenant cluster ID.
* A price exporter exports all pricing information which it collected from Lieutenant and and product database, mainly an ERP. This metrics are also labeled with an identifier for later PromQL matching.
* Price calculation and summing up is done in pure PromQL.
* An invoice creator queries the TSDB to generate invoice lines and write them either directly into the ERP or in a portable data format for import into billing system.

This design allows to implement different billing models even for the same Kubernetes cluster, for example for reselling models.

=== User Stories

==== Private Kubernetes Cluster Billing

In this story the whole cluster belongs to one tenant, all services running on this cluster and the cluster itself is being billed to the same tenant.

...

==== Services on shared Kubernetes Cluster Billing

In this story the cluster itself doesn't belong to one tenant and it hosts many services belonging to different tenants.

...

==== Service Reselling

In this story the cluster itself belongs to a service provider which resells services on top of the cluster to its end-user.

...


=== Implementation Details/Notes/Constraints [optional]

==== Billing metrics collection with Prometheus

While the metrics needed depends on the product unit being billed, in general metrics are collected from various metrics exporter like https://github.com/kubernetes/kube-state-metrics[kube-state-metrics] directly on the source Kubernetes cluster. Which exporters will be needed have to be defined per unit to be billed in the product definition, it could even be that a specific exporter has to be written. There is no special requirement to the exported metrics.

==== Billing metrics transport with Telemeter

Billing metrics will be transported over a secure and authenticated connection to a central billing metric store as these metrics are considered very important. Only metrics needed for the billing system are transported.

Metrics from the source cluster must have cluster or tenant identifying labels, otherwise they are not allowed.

Metric transport is achieved by making use of https://github.com/openshift/telemeter[Telemeter], which describes the process like this:

[quote, github.com/openshift/telemeter/README.md]
____
. The local client scrapes `/federate` on a given Prometheus instance.
. The local client performs cleanup and anonymization and then pushes the metrics to the server.
. The server authenticates the client, validates and verifies that the metrics are "safe", and then ensures they have a label uniquely identifying the source client.
. The server holds the metrics in a local disk store until scraped.
. A centralized Prometheus scrapes each server instance and aggregates all the metrics.
____

TODO:

* Research configuration details of Telemeter
* Describe authentication (idea: install Telemeter server on the same cluster as Lieutenant and use a Kubernetes service account as authentication token)
* Who scrapes the telemeter server? Thanos receive via forward-url? Or Prometheus scraper which also scrapes price exporters?

==== Central billing metric store with Thanos

Billing metrics will be received by https://thanos.io/components/receive.md/[Thanos receiver]. In front of the Thanos receiver is the central billing metric store authentication proxy.

==== Billing metrics identifier labels

For being able to generate invoices billing metrics must be identifiable for example by the cluster or tenant ID.

This identifier is used throughout the system, be that for PromQL queries or by the invoice generator.

The following labels are recommended to be used:

* `lieutenant_cluster_id`: The Lieutenant Cluster ID
* `lieutenant_tenant_id`: The Lieutenant Tenant ID

These labels need special treatment in regards to tampering protection, mainly if metrics are coming from untrusted source clusters. See section about the metric store proxy for more details.

==== The role of the product definition

==== Billing data exporter(s)

Pricing, product and customer information must be available as metrics in Prometheus to calculate the billing units. These metrics must contain a defined set of labels so that label joining and calculation will be possible.

These exporters will have to be custom made, depending on the available source data store, for example the ERP. The example here is using Odoo as the source of product, price and customer information.

It is important that the produced metric is exactly ...

[cols=",,",options="header",]
|===
|Exporter
|Description
|Metric Example

|Lieutenant
|Exporting of all information about clusters and tenants.
a|
----
lieutenant_cluster{lieutenant_cluster_id="cluster-42",lieutenant_tenant_id="tenant-42",cloud="gcp",distribution="openshift4",region="eu-central-1",service_level="premium"} 1
lieutenant_tenant{lieutenant_tenant_id="tenant-42",display_name="Acme Corp"} 1
----

|Product and Price
|Information about products and prices, coming from the source data store, for example from the ERP.
a|
----
erp_product{cloud="gcp",distribution="openshift4",service_level="premium",product_id="ComputeOpenShiftHyperscalerPremium"} 2.20
----

|Customer
|tbd
a|tbd

|===

==== Price calculation

* PromQL
* Recording rules
* Billing unit
* Mark end of service

==== Invoice generator

* Invoice line
* Grouping
* Iterate over available series for the timeframe, get customer and cluster ids -> not from Lieutenant

==== Handling disconnected clusters

https://prometheus.io/docs/prometheus/latest/querying/api/#snapshot

==== Solve missing metrics

==== Testing

==== Terminology

Source Cluster:: Kubernetes cluster containing resources to be billed
Private Cluster:: Kubernetes cluster belonging to one tenant
Shared Cluster:: Kubernetes cluster which hosts services for several tenants
Billing Unit:: Invoice line, a unit which will appear on the invoice
Billing Metric:: Metrics used to bill units
Service Reselling:: One service provider provides a private cluster to another service provider which in turn sells services running on this private cluster to its own customers.

=== Risks and Mitigations

* Missing metrics / gaps
* Tampering with source metrics labels

== Drawbacks [optional]

* Correct wrong invoices?

== Alternatives [optional]

* Cyclops
* Commercial tool

== References

== TODO

* Include cloud costs / cloud costs exporter