= SDD 0028 - Reusable Commodore Component Configuration Packages

:sdd_author:    Simon Gerber
:sdd_owner:     Tarazed
:sdd_reviewers: TBD
:sdd_date:      2022-04-29
:sdd_status:    draft
\include::partial$meta-info-table.adoc[]

[NOTE]
.Summary
====
The SDD documents a design for reusable Commodore component configuration packages.

The SDD defines how packages are distributed and included in the config hierarchy, and describes how the packages can be tested in CI (for example GitHub actions).
====

== Motivation

Recently, we've seen that Commodore components have provided more generic defaults.
One example component which has very generic and minimal defaults is https://github.com/projectsyn/component-syn-kube-prometheus[syn-kube-prometheus].
While this approach makes the component very versatile -- it can be used to setup a Prometheus-operator based monitoring stack with exactly the desired components -- there's a risk that the same configurations will be replicated in many places, or that configurations will be distributed in an ad-hoc fashion.

To avoid a proliferation of large ad-hoc configuration bundles, this SDD presents a mechanism to package such configurations in a form suitable for reuse and distribution.
Additionally, by formalizing the packaging of configuration bundles, we can ensure that the chosen format is suitable to allow testing of the packaged configurations.

Currently, we already use an ad-hoc mechanism for reusable configurations in the VSHN https://git.vshn.net/syn/commodore-defaults[Commodore defaults repo (internal)].
The Commodore defaults repo provides some classes with reusable configurations in folder `apps`.
These classes can be included in tenants or clusters by including class `global.apps.<name>`.
While this approach addresses distribution within an organization, it falls short on both reusability in the wider Project Syn ecosystem and testability.

=== Goals

* Provide a mechanism to package and distribute Commodore component configurations.
* The design must ensure that configuration packages can be tested in CI.

=== Non-Goals

* Programmatic manipulation of component defaults

== Design Proposal

We propose that each Commodore component configuration package is a Git repository.
This gives us change history and versioning of configuration packages based on a well-established toolset.
Making each configuration package a Git repository also fits well with the Project Syn approach of keeping all dependencies (global and tenant config, components) in Git.
We can also profit from all the already existing logic for cutting releases, and CI tests which we've engineered for Commodore components.

The big design question is revolves around the mechanism used to fetch configuration packages.
We can either fetch configuration packages using Kapitan's remote inventory support or we can enhance Commodore's native dependency fetching logic to support config packages in addition to components.

=== Approach 1: Use Kapitan's remote inventory support

The first option for fetching config packages during catalog compilation is based on Kapitan's remote inventory support.
By reusing an existing Kapitan feature we get nice integration into the config hierarchy for free.
Also, by integrating a Kapitan feature, the amount of new code in Commodore is fairly small (on the order of tens of lines).

However, by using Kapitan's remote inventories, we're constrained by the options which are available.
Remote inventories are defined in a reclass list.
Unfortunately, this means that we can't easily adjust already included remote inventories further down in the config hierarchy.
Additionally, Kapitan's remote inventory definitions don't separate dependency specification and fetching.

Finally, using Kapitan's remote inventory support will require Commodore to make additional calls to internal Kapitan functions.
While this hasn't posed a problem so far, the tight coupling by calling Kapitan internals may cause increased maintenance cost in the future.

=== Approach 2: Enhance Commodore's dependency fetching logic

The second option for fetching config packages during catalog compilation is to implement native support in Commodore for specifying and fetching config packages.
This approach has the advantage that we can closely mimic the configuration structures used to define and include components in the configuration hierarchy.
Having similar structures for specifying and including components and config packages should reduce the amount of extra configuration complexity for the users of the new feature.

By using Commodore's dependency fetching, we can easily separate configuration package dependency specification and fetching.
Additionally, we can control exactly where we download config packages to and how we make them available in the configuration hierarchy.

Finally, we add less complexity to the actual catalog compilation by being able to tailor the implementation exactly to our needs.

The downside of the Commodore-native approach is that we reimplement a feature which is already provided by Kapitan.
Implementing native configuration package fetching also increases the size and complexity of the Commodore code base more than reusing a Kapitan feature.

=== Testability

To test Commodore component configuration packages, we will introduce a new Commodore command to compile a complete package.
This command will work similarly to `commodore component compile` but will be executed for a package instead of a component.
The command will use an additional test class which has to provide `parameters.components` with entries for any components that the package includes.
With the information provided by the test class, the command will fetch the referenced components before compiling the package.

A configuration package template which provides GitHub actions and a Makefile will be provided by Project Syn.
The template will allow users to ensure consistent test and CI configurations for new Commodore component configuration packages.
Together with the template, a mechanism to merge template updates into existing configuration packages will be provided.

=== Implementation Details/Notes/Constraints

The implementation of configuration packages needs to be integrated into the existing catalog compilation logic.
Commodore must be able to compile hierarchies which use configuration packages using the same commands as hierarchies which don't use any configuration packages.

Commodore's `kapitan_inventory()` needs to be extended to optionally ignore missing classes.
This is necessary, as we otherwise won't be able to parse the hierarchy to determine which configuration packages need to be fetched.

Regardless of the chosen mechanism to fetch configuration packages, Commodore needs to fetch configuration packages before fetching components.
This is required to ensure that configuration packages can specify components to include in the catalog compilation.

For testing we should use a similar approach to component testing, but fetch components defined by the config package first.
We probably need to implement a new Commodore command to support standalone compilation of a full configuration package.

=== Risks and Mitigations

[horizontal]
Risk:: Config packages can't be tested easily
Mitigation:: Add whatever support is necessary in Commodore to allow compiling minimal catalog using the config package

== Alternatives

=== Ad-hoc configuration packages in the global defaults

We could just document the approach used in the VSHN global defaults at the moment.
This approach doesn't need any changes in Commodore.
However, the approach doesn't offer any support for testing configuration packages.

Finally, with this approach, there's no clear boundary between regluar global configurations and config packages.

=== Fetching approach we decide against

*TODO: fill in this section with the config package fetching approach we end up not picking.*

== References

* https://kapitan.dev/inventory/#inventory-classes
* https://syn.tools/commodore/reference/architecture.html#_dependency_fetching
