= Getting Started with Project Syn

This guide helps to get started with the various Project Syn tools.

== Requirements

Before you start, please check the following requirements:

* A GitLab account.
* The following tools:
** `kubectl`
** `k3d`
** `jq`
** `curl`

Modify your `/etc/hosts` file and add the following entry:

[source]
--
127.0.0.1       host.k3d.internal
--

Launch two new K3s clusters with `k3d`:

[source,bash]
--
k3d cluster create lieutenant --port "35777:8080@loadbalancer" --image=rancher/k3s:v1.23.8-k3s1
--

and

[source,bash]
--
k3d cluster create steward  --port "35778:8080@loadbalancer" --image=rancher/k3s:v1.23.8-k3s1
--

In your GitLab account, create a token with the 'API' scope at https://gitlab.com/-/profile/personal_access_tokens.

Create the following environment variables. The `GITLAB_TOKEN` variable contains the value of the token created previously.

[source,bash]
--
export GITLAB_USERNAME=johndoe        # Use your own GitLab username
export GITLAB_ENDPOINT=gitlab.com     # Or your own GitLab instance URL
export GITLAB_TOKEN=xxxxxxxxxxxxxxxx
--

== Lieutenant

Lieutenant is the central inventory service for all Project Syn-managed clusters. It consists of the Lieutenant _Operator_ and the Lieutenant _API_. Lieutenant needs API access to a GitLab server to create and manage Git repositories for clusters and tenants.

Lieutenant is the central API for all other Project Syn tools. Therefore we will install it first so that all other components can do their job.

Install Lieutenant on the "lieutenant" cluster with the following command:

[source,bash]
----
curl -fsL https://try.syn.tools | bash
----

At the end of this procedure, you will have a K3s cluster in your computer, running the Lieutenant API and Operator.

You can explore Lieutenant using `kubectl` running the following command:

[source,bash]
--
kubectl --context k3d-lieutenant get tenants -n lieutenant
--

The command above returns something like the following:

[source]
--
NAME             DISPLAY NAME         AGE
t-aged-pond-24   Project Syn Tenant   13s
--

In the context of Project Syn, a "tenant" is an entity to whom clusters are assigned. Tenants could be customers, departments, teams, or any entity responsible for owning a cluster.

Project Syn stores cluster-specific configuration values in that tenant's own configuration Git repository. You should now have a new project in your GitLab account called "Project Syn Tenant."

== Steward

Steward is the in-cluster agent of Project Syn. It runs in each cluster associated with a tenant, automatically reacting to changes in the configuration stored in the corresponding Git repositories.

Install Steward in K3s with one simple command:

[source,bash]
--
curl -fsL https://try.syn.tools/steward | bash
--

The installation of Steward happens on the K3s cluster via an install URL provided by Lieutenant, using a one-time bootstrap token. The token is only valid once and only for 30 minutes after cluster registration.

Once Steward is installed on the K3s cluster, you can see its pod running:

[source,bash]
--
kubectl --context k3d-steward -n syn get pod
--

At this point, Lieutenant is aware of the new K3s cluster, and we can see that through the following command:

[source,bash]
--
kubectl --context k3d-lieutenant get clusters -n lieutenant
--

The command above outputs something similar to this:

[source]
--
NAME                  DISPLAY NAME          TENANT                  AGE
c-long-firefly-9017   Project Syn Cluster   t-autumn-silence-6912   12s
--

Cluster names have the `c-` prefix, while tenant names have with `t-` prefix.

Steward wraps https://argoproj.github.io/cd/[Argo CD], a Cloud-Native continuous deployment and integration tool, continuously observing the GitLab repositories for changes.

You can also connect to Argo CD and see its console. Start by exposing the `argocd-server` deployment:

[source,bash]
----
kubectl --context k3d-steward -n syn expose deployment argocd-server --type=LoadBalancer --port=8080
----

Open Argo CD in your browser at http://localhost:35778. Log in to Argo CD with the username `admin` and the password returned by this command:

[source,bash]
----
kubectl --context k3d-steward -n syn get secret steward -o json | jq -r .data.token | base64 --decode
----

After these steps, the local K3s cluster is now Syn enabled, and a Git repository called "Project Syn Cluster" is stored in GitLab.

// == Next Steps

// This guide provides a quick overview of Lieutenant and Steward. If you are interested in knowing more about Project Syn, proceed to the second part to learn about Commodore, the third major component of Project Syn.

== Cleaning Up

Once you've gone through all these steps, you can cleanup all generated stuff using the following steps:

. Delete the cluster and tenant objects, removing the GitLab projects at the same time:
+
[source,bash]
----
curl -fsL https://try.syn.tools/cleanup | bash
----

. Remove the K3d clusters:
+
[source,bash]
----
k3d cluster delete --all
----
