= Project Syn

image::logo_projectsyn.svg[]

[discrete]
== Introduction

> Project Syn is a set of tools helping to securely manage a fleet of Kubernetes clusters. It brings a hierarchical configuration management based on GitOps principles, reusable components and an inventory of information about all Kubernetes clusters.

See xref:about/introduction.adoc[introduction] for a more detailed description about what Project Syn offers. If you would like to get in touch with us have a look at xref:about/community.adoc[community] for ways how to do that.

TIP: The xref:tutorials/getting-started.adoc[Getting Started] gives you a glimpse into Project Syn. Give it a try!

[discrete]
== Overview of Project Syn tools

xref:commodore::index.adoc[Commodore]:: Hierarchical Configuration Management with Kapitan.
xref:lieutenant-operator::index.adoc[Lieutenant Operator]:: Kubernetes operator providing the business logic for the API.
xref:lieutenant-api::index.adoc[Lieutenant API]:: REST API for cluster management.
xref:steward::index.adoc[Steward]:: In-Cluster agent.

[discrete]
=== Related tools

Tools we created but aren't strictly related to Project Syn.

xref:floodgate::index.adoc[Floodgate]:: Floodgate controls https://github.com/rancher/system-upgrade-controller[SUC] channels

[discrete]
== Documentation

The documentation is inspired by the https://documentation.divio.com/[Divio's documentation structure]:

Tutorials:: _Learning-oriented_: a lesson which teaches you something around Project Syn.

How-to guides:: _Problem-oriented_: step-by-step guides to achieve a goal.

Technical reference:: _Information-oriented_: description about the inner ongoings of Project Syn.

Explanation:: _Understanding-oriented_: explains the background.
