= Project Syn Roadmap

This page lists the high level roadmap of Project Syn. It will be under constant change.

> It's done when it's done

NOTE: We release the tools independently, this page contains a list of ideas throughout all Project Syn tools.

== Planned

Features which we're confident are being implemented:

Commodore::
* Make catalog compilation much faster than it's today (Rewrite Reclass in Rust).
* Introduce component dependency handling.
* Rework UX of CLI.
* Support for decentralized GitOps repositories.
* Create merge requests on catalog generation (policy-based, similar to Renovate).
* Local development environment for simpler Commodore Component development.

Lieutenant::
* Remove Lieutenant API and make it a 100% Kubernetes API.
* Component version reporting, so that it's known which Component versions are used where.

== Vision

Features which are part of our vision and therefore have uncertainty of being implemented:

* Project Syn Control Plane as a Service (So you don't have to care of running Lieutenant, Vault and other stuff needed).
* Renewed "Getting Started" experience to make it much easier to start with Project Syn.
* Decentralized catalog compilation, for example directly on the destination cluster.
* Make Commodore Components usable standalone, without requiring Lieutenant and Steward.
* Automated secret generation in Vault on cluster creation.
* Support for other Git repository hosting than GitLab (for example GitHub, Gitea, Forgejo)
* Git commit signing of Commodore catalogs and only allow properly signed catalogs on clusters

== Older Releases

See the GitHub Releases for each tool:

* https://github.com/projectsyn/commodore/releases[Commodore^]
* https://github.com/projectsyn/lieutenant-operator/releases[Lieutenant Operator^]
* https://github.com/projectsyn/lieutenant-api/releases[Lieutenant API^]
* https://github.com/projectsyn/steward/releases[Steward^]
