= Project Syn Tools Release Process

Releases often just require a new SemVer tag with `v`-prefix to be pushed, for example `v1.2.3`.
The changelog and GitHub release will then be generated automatically.

All Project Syn Tools that require the container image tag to be in sync with the release, require additional preparation:

. Create a release branch
+
[source,shell]
----
git checkout -b prepare-release
----

. Edit `deploy/kustomization.yaml` to point to the to-be-released version
.. On Lieutenant API also update the Steward tag in `deploy/deployment.yaml`: Environment variable `STEWARD_IMAGE`.

. Commit and push the changes and create a Pull Request
+
[source,shell]
----
git commit -a -m "Prepare release vX.Y.Z"
git push -u
----

. Check and update xref:tutorials/getting-started.adoc[Getting Started guide] and https://syn.tools/tuto/index.html[Tutorial: Writing your First Commodore Component] (These guides need to be up-to-date and work 100% all the time)

== Additional work for major releases

If a "major" release is being done, the following additional work needs to be done:

* Update the https://github.com/projectsyn/documentation/blob/master/docs/modules/ROOT/pages/roadmap.adoc[Roadmap]
* Write a blogpost and spread it on social media
* Close the associated GitHub project and internal Jira project (if applicable)
